# Generated by Django 4.2.7 on 2023-11-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_alter_sudokuimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudokuimage',
            name='image',
            field=models.ImageField(upload_to='sudoku_images/'),
        ),
    ]
